version: "3.8"

services:
  flood:
    image: jesec/flood:latest
    container_name: flood
    restart: unless-stopped

    ports:
      - "8000:3000"

    environment:
      - HOME=/config
      - FLOOD_OPTION_host=0.0.0.0
      - FLOOD_OPTION_port=3000

    volumes:
      - flood-data:/config

volumes:
  flood-data: