version: "3.8"

services:
  flood:
    image: jesec/flood:latest
    container_name: flood
    restart: unless-stopped

    ports:
      - "8000:3000"

    environment:
      - HOME=/config
      - FLOOD_OPTION_host=0.0.0.0
      - FLOOD_OPTION_port=3000

      # flood login
      - FLOOD_OPTION_username=${FLOOD_USER}
      - FLOOD_OPTION_password=${FLOOD_PASS}

    volumes:
      - flood-data:/config

    user: "0:0"

volumes:
  flood-data: